name: Build
on: [push, pull_request]

jobs:
    deploy:
        name: build dependencies & create artifact
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2.0.0

            # Install PHP dependencies (Production ONLY)
            - name: Install composer dependencies
              run: composer install --no-dev -o

            # Remove development files
            - name: Clean-up project
              uses: PrestaShopCorp/github-action-clean-before-deploy@v1.0

            # Zip files and upload to artifacts list
            - name: Create & upload artifact
              uses: actions/upload-artifact@v1
              with:
                  name: ${{ github.event.repository.name }}
                  path: ../
